(()=>{
'use strict';
const VERSION='MVP Ver.1.7',CHANGE='ケース・バラ在庫 / 先期限先出し使用';
const n=v=>Math.max(0,Math.floor(Number(v)||0)),packOf=p=>Math.max(1,n(p&&p.casePack)||1);
const split=(q,p)=>({cases:p>1?Math.floor(n(q)/p):0,loose:p>1?n(q)%p:n(q)});
const fmt=(q,p)=>{const s=split(q,p);return p>1?`${s.cases}ケース＋${s.loose}バラ（計${n(q)}）`:`${n(q)}個`;};
const el=id=>document.getElementById(id);
function setupProductPack(){const supplier=el('productSupplier');if(!supplier||el('productCasePack'))return;const wrap=document.createElement('div');wrap.innerHTML='<label>1ケースの入数</label><input id="productCasePack" type="number" min="1" inputmode="numeric" placeholder="例：20"><div class="muted" style="margin-top:4px">ケース管理しない商品は空欄で構いません。</div>';supplier.parentElement.insertAdjacentElement('afterend',wrap);const originalPut=put;put=function(name,obj){if(name==='products'&&el('view-addProduct')&&!el('view-addProduct').classList.contains('hidden')){const v=n(el('productCasePack')&&el('productCasePack').value);if(v>0)obj.casePack=v;}return originalPut(name,obj);};const btn=el('addProductBtn');if(btn)btn.addEventListener('click',()=>{const p=Math.max(1,n(el('productCasePack')&&el('productCasePack').value)||1),c=n(el('productInitialCases')&&el('productInitialCases').value),l=n(el('productInitialLoose')&&el('productInitialLoose').value);if(el('productQty'))el('productQty').value=c*p+l;},true);}
function setupInitialStock(){const qty=el('productQty');if(!qty||el('productInitialCases'))return;const parent=qty.parentElement;parent.innerHTML='<label>ケース数</label><input id="productInitialCases" type="number" min="0" inputmode="numeric" placeholder="0">';const loose=document.createElement('div');loose.innerHTML='<label>バラ数</label><input id="productInitialLoose" type="number" min="0" inputmode="numeric" placeholder="0">';parent.insertAdjacentElement('afterend',loose);qty.type='hidden';qty.value='0';parent.appendChild(qty);}
function setupReceiving(){const old=el('lotQty');if(!old||el('lotCases'))return;const parent=old.parentElement;parent.innerHTML='<label>ケース数</label><input id="lotCases" type="number" min="0" inputmode="numeric" placeholder="0">';const loose=document.createElement('div');loose.innerHTML='<label>バラ数</label><input id="lotLoose" type="number" min="0" inputmode="numeric" placeholder="0">';parent.insertAdjacentElement('afterend',loose);old.type='hidden';old.value='0';parent.appendChild(old);const btn=el('addLotBtn');if(btn){const original=btn.onclick;btn.onclick=async()=>{const p=await getOne('products',currentProductId),pack=packOf(p),c=n(el('lotCases').value),l=n(el('lotLoose').value),total=c*pack+l;if(total<=0)return alert('ケース数またはバラ数を入力してください');old.value=total;await original();el('lotCases').value='';el('lotLoose').value='';};}}
async function renderCaseLots(productId){const p=await getOne('products',productId),pack=packOf(p),lots=(await getAll('lots')).filter(x=>x.productId===productId&&Number(x.qty)>0).sort((a,b)=>(a.expiry||'9999-99-99').localeCompare(b.expiry||'9999-99-99')),box=el('lotList');box.innerHTML='';if(!lots.length){box.innerHTML='<div class="empty">在庫ロットがありません</div>';return;}for(const l of lots){const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="item-title">${fmt(l.qty,pack)}</div><div class="muted">賞味期限：${l.expiry||'未登録'}</div>`;box.appendChild(d);}}
function setupUsageUI(){const detail=el('view-productDetail');if(!detail||el('useStockCard'))return;const lotList=el('lotList'),anchor=lotList&&lotList.nextElementSibling;if(!anchor)return;const card=document.createElement('div');card.id='useStockCard';card.innerHTML='<h3>使用登録</h3><p class="muted">賞味期限が近い在庫から自動で使用します。バラが足りない場合はケースを自動で開封します。</p><div id="casePackInfo" class="notice"></div><div class="row"><div><label>使用ケース数</label><input id="useCases" type="number" min="0" inputmode="numeric" placeholder="0"></div><div><label>使用バラ数</label><input id="useLoose" type="number" min="0" inputmode="numeric" placeholder="0"></div></div><div class="row" style="margin-top:10px"><button id="useStockBtn">使用して在庫を減らす</button><button id="changeCasePackBtn" class="secondary">ケース入数を変更</button></div><hr>';anchor.parentElement.insertBefore(card,anchor);el('changeCasePackBtn').onclick=async()=>{const p=await getOne('products',currentProductId),v=prompt('1ケースの入数を入力してください。ケース管理しない場合は1です。',p.casePack||'');if(v===null)return;const pack=n(v);if(pack<1)return alert('1以上の入数を入力してください');p.casePack=pack;await put('products',p);await refreshInfo();await renderCaseLots(p.id);alert(`1ケース＝${pack}個で保存しました。`);};el('useStockBtn').onclick=useFEFO;}
async function refreshInfo(){if(!currentProductId||!el('casePackInfo'))return;const p=await getOne('products',currentProductId),pack=packOf(p),total=await currentProductTotal(p.id);el('casePackInfo').textContent=pack>1?`1ケース＝${pack}個　現在庫：${fmt(total,pack)}`:`現在庫：${fmt(total,pack)}　※ケース入数未設定`;el('useCases').disabled=pack<=1;}
async function useFEFO(){const p=await getOne('products',currentProductId),pack=packOf(p),want=n(el('useCases').value)*pack+n(el('useLoose').value);if(want<=0)return alert('使用する数量を入力してください');const lots=(await getAll('lots')).filter(x=>x.productId===p.id&&n(x.qty)>0).sort((a,b)=>(a.expiry||'9999-99-99').localeCompare(b.expiry||'9999-99-99')),available=lots.reduce((s,l)=>s+n(l.qty),0);if(want>available)return alert(`在庫が不足しています。現在庫は${fmt(available,pack)}です。`);if(!confirm(`${fmt(want,pack)}を使用します。\n賞味期限が近い在庫から自動で減算します。`))return;let remaining=want,used=[];for(const lot of lots){if(remaining<=0)break;const take=Math.min(remaining,n(lot.qty));lot.qty=n(lot.qty)-take;await put('lots',lot);remaining-=take;const balance=await currentProductTotal(p.id);await addTransaction({productId:p.id,lotId:lot.id,type:'使用',qty:-take,balance,note:'賞味期限の近いロットから自動減算'});used.push(`${lot.expiry||'期限未登録'}：${take}個`);}el('useCases').value='';el('useLoose').value='';await renderCaseLots(p.id);await renderLotStocktake(p.id);await renderDiscardLots(p.id);await refreshInfo();alert(`使用登録しました。\n${used.join('\n')}`);}
function init(){try{setupProductPack();setupInitialStock();setupReceiving();if(typeof renderLots==='function')renderLots=renderCaseLots;setupUsageUI();if(typeof openProduct==='function'){const original=openProduct;openProduct=async function(id){await original(id);await refreshInfo();};}const sub=document.querySelector('header .sub');if(sub)sub.textContent=`${VERSION} / ${CHANGE} / 端末内保存`;}catch(e){console.error('case-stock init',e);}}
window.addEventListener('load',()=>setTimeout(init,650));
})();