const CACHE_NAME = 'inventory-pwa-v1-21-receiving-compat';
const CURRENT_VERSION = 'MVP Ver.1.21 / 入荷互換処理整理 / 端末内保存';
const FEATURE_FILES=['jan-scanner.js','case-stock.js','date-wheel.js','location-order.js','location-status.js','product-status.js'];
const ASSETS = ['./manifest.webmanifest','./icon-192.png','./icon-512.png',...FEATURE_FILES.map(f=>'./'+f)];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(ASSETS)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim();});
async function fixedIndexResponse(request){try{const network=await fetch(request,{cache:'no-store'});let html=await network.text();if(!html.includes('id="editProductMasterBtn"'))html=html.replace('<div id="detailLocation" class="muted"></div>','<div id="detailLocation" class="muted"></div>\n<button class="ghost" id="editProductMasterBtn" style="margin-top:10px">商品情報を編集</button>');for(const f of FEATURE_FILES)if(!html.includes(f))html=html.replace('</body>',`<script src="./${f}"></script>\n</body>`);html=html.replace(/MVP Ver\.1\.[0-9]+(?: \/ [^<]*)? \/ 端末内保存/g,CURRENT_VERSION);
 const oldQuickAdd="document.getElementById('quickAddLot').onclick=async()=>{const products=(await getAll('products')).filter(x=>x.active!==false);if(!products.length){alert('先に商品を登録してください');return showView('addProduct')}showView('inventory')};";const newQuickAdd="window.openQuickAddLot=async()=>{const products=(await getAll('products')).filter(x=>x.active!==false);if(!products.length){alert('先に商品を登録してください');return showView('addProduct')}showView('inventory')};";if(html.includes(oldQuickAdd))html=html.replace(oldQuickAdd,newQuickAdd);
 const legacyReceiving=/<hr>\s*<h3>入荷・賞味期限を追加<\/h3>\s*<div class="row">[\s\S]*?<button id="addLotBtn">追加登録<\/button><\/div>/;html=html.replace(legacyReceiving,'<button id="addLotBtn" class="hidden" type="button" aria-hidden="true" tabindex="-1"></button><input id="lotQty" class="hidden" type="number" aria-hidden="true"><input id="lotExpiry" class="hidden" type="date" aria-hidden="true">');
 const legacyHome=`<div class="grid">\n        <button class="big" data-view="inventory">在庫を見る</button>\n        <button class="big" id="quickAddLot">入荷・期限登録</button>\n        <button class="big" data-view="expiry">賞味期限を確認</button>\n        <button class="big" data-view="stocktake">棚卸する</button>\n        <button class="big" data-view="allHistory">全体履歴を見る</button>\n        <button class="big" data-view="addProduct">＋ 商品登録</button>\n        <button class="big" data-view="settings">設定</button>\n      </div>`;if(html.includes(legacyHome))html=html.replace(legacyHome,'');const guard=`<script>(()=>{const V=${JSON.stringify(CURRENT_VERSION)};const apply=()=>{const s=document.querySelector('header .sub');if(s&&s.textContent!==V)s.textContent=V;};apply();new MutationObserver(apply).observe(document.documentElement,{subtree:true,childList:true,characterData:true});})();<\/script>`;html=html.replace('</body>',guard+'\n</body>');const response=new Response(html,{status:network.status,statusText:network.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'}});const cache=await caches.open(CACHE_NAME);cache.put('./index.html',response.clone());return response;}catch(e){return(await caches.match('./index.html'))||new Response('アプリを読み込めませんでした。',{status:503});}}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);const isIndex=url.origin===self.location.origin&&(url.pathname.endsWith('/inventory-pwa/')||url.pathname.endsWith('/inventory-pwa/index.html'));if(isIndex){event.respondWith(fixedIndexResponse(event.request));return;}if(FEATURE_FILES.some(f=>url.pathname.endsWith('/'+f))){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{const clone=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,clone));return response;}).catch(()=>caches.match(event.request)));return;}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{const clone=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,clone));return response;}).catch(()=>caches.match(event.request))));});