const CACHE_NAME = 'inventory-pwa-v1-26-recovery-2';
const CURRENT_VERSION = 'MVP Ver.1.26 / バージョン表示整理 / 端末内保存';
const FEATURE_FILES=['jan-scanner.js','case-stock.js','date-wheel.js','location-order.js','location-status.js','product-status.js'];
const LOADER_FILE='app-loader.js';
const ASSETS = ['./manifest.webmanifest','./icon-192.png','./icon-512.png','./'+LOADER_FILE,...FEATURE_FILES.map(f=>'./'+f)];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(ASSETS)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim();});
async function fixedIndexResponse(request){try{const network=await fetch(request,{cache:'no-store'});if(!network.ok)throw new Error(`index response ${network.status}`);const type=network.headers.get('content-type')||'';if(!type.includes('text/html'))throw new Error(`unexpected content-type: ${type}`);let html=await network.text();if(!html.includes('<body'))throw new Error('invalid index html');if(!html.includes('id="editProductMasterBtn"'))html=html.replace('<div id="detailLocation" class="muted"></div>','<div id="detailLocation" class="muted"></div>\n<button class="ghost" id="editProductMasterBtn" style="margin-top:10px">商品情報を編集</button>');if(!html.includes(LOADER_FILE))html=html.replace('</body>',`<script src="./${LOADER_FILE}"></script>\n</body>`);html=html.replace(/MVP Ver\.1\.[0-9]+(?: \/ [^<]*)? \/ 端末内保存/g,CURRENT_VERSION);
 const legacyReceiving=/<hr>\s*<h3>入荷・賞味期限を追加<\/h3>\s*<div class="row">[\s\S]*?<button id="addLotBtn">追加登録<\/button><\/div>/;html=html.replace(legacyReceiving,'<div class="hidden" aria-hidden="true"><button id="addLotBtn" type="button" tabindex="-1"></button><input id="lotQty" type="number"><input id="lotExpiry" type="date"></div>');
 const legacyHome=`<div class="grid">\n        <button class="big" data-view="inventory">在庫を見る</button>\n        <button class="big" id="quickAddLot">入荷・期限登録</button>\n        <button class="big" data-view="expiry">賞味期限を確認</button>\n        <button class="big" data-view="stocktake">棚卸する</button>\n        <button class="big" data-view="allHistory">全体履歴を見る</button>\n        <button class="big" data-view="addProduct">＋ 商品登録</button>\n        <button class="big" data-view="settings">設定</button>\n      </div>`;if(html.includes(legacyHome))html=html.replace(legacyHome,'<div class="hidden" aria-hidden="true"><button id="quickAddLot" type="button" tabindex="-1"></button></div>');const response=new Response(html,{status:200,statusText:'OK',headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'}});const cache=await caches.open(CACHE_NAME);cache.put('./index.html',response.clone());return response;}catch(e){console.warn('index load fallback',e);return(await caches.match('./index.html'))||new Response('アプリを読み込めませんでした。通信状態を確認して再読み込みしてください。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});}}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);const isIndex=url.origin===self.location.origin&&(url.pathname.endsWith('/inventory-pwa/')||url.pathname.endsWith('/inventory-pwa/index.html'));if(isIndex){event.respondWith(fixedIndexResponse(event.request));return;}if(url.pathname.endsWith('/'+LOADER_FILE)||FEATURE_FILES.some(f=>url.pathname.endsWith('/'+f))){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`feature response ${response.status}`);const clone=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,clone));return response;}).catch(()=>caches.match(event.request)));return;}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response.ok){const clone=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,clone));}return response;}).catch(()=>caches.match(event.request))));});