(()=>{
'use strict';
const $=id=>document.getElementById(id);const views=[...document.querySelectorAll('.view')];
function show(id){views.forEach(v=>v.classList.toggle('hidden',v.id!==id));window.scrollTo(0,0);}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200);}
async function setting(key){return (await InventoryDB.get('settings',key))?.value;}
async function setSetting(key,value){await InventoryDB.put('settings',{key,value});}
async function refreshHome(){const [locations,products,lots]=await Promise.all([InventoryDB.getAll('locations'),InventoryDB.getAll('products'),InventoryDB.getAll('lots')]);$('storeName').textContent=await setting('storeName')||'';$('productCount').textContent=products.filter(p=>p.active!==false).length;$('stockCount').textContent=lots.reduce((s,l)=>s+Number(l.qty||0),0);const activeLoc=locations.filter(x=>x.active!==false);const roots=activeLoc.filter(x=>!x.parentId).sort((a,b)=>(a.displayNumber??Infinity)-(b.displayNumber??Infinity)||String(a.name).localeCompare(String(b.name),'ja'));$('locationList').innerHTML=roots.length?'':'<div class="empty">保管場所はまだありません。</div>';for(const root of roots){const children=activeLoc.filter(x=>x.parentId===root.id).sort((a,b)=>(a.displayNumber??Infinity)-(b.displayNumber??Infinity)||String(a.name).localeCompare(String(b.name),'ja'));const e=document.createElement('div');e.className='list-item';e.innerHTML=`<strong>${escapeHtml((root.displayNumber!=null?root.displayNumber+'. ':'')+root.name)}</strong><small>${escapeHtml(children.map(x=>x.name).join(' / ')||'棚・区画なし')}</small>`;$('locationList').appendChild(e);}const activeProducts=products.filter(p=>p.active!==false).sort((a,b)=>String(a.name).localeCompare(String(b.name),'ja'));$('productList').innerHTML=activeProducts.length?'':'<div class="empty">商品はまだありません。</div>';for(const p of activeProducts){const loc=locations.find(x=>x.id===p.locationId);const qty=lots.filter(l=>l.productId===p.id).reduce((s,l)=>s+Number(l.qty||0),0);const e=document.createElement('div');e.className='list-item';e.innerHTML=`<strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(loc?.name||'保管場所未設定')} / 在庫 ${qty}個${p.casePack>1?' / 1ケース '+p.casePack+'個':''}</small>`;$('productList').appendChild(e);}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function fillLocationOptions(){const locations=(await InventoryDB.getAll('locations')).filter(x=>x.active!==false);$('locationParent').innerHTML='<option value="">なし（大分類）</option>'+locations.filter(x=>!x.parentId).map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');$('productLocation').innerHTML='<option value="">選択してください</option>'+locations.map(x=>{const parent=locations.find(p=>p.id===x.parentId);return `<option value="${x.id}">${escapeHtml(parent?parent.name+' ＞ '+x.name:x.name)}</option>`;}).join('');}
async function goHome(){await refreshHome();show('homeView');}
$('saveSetupBtn').onclick=async()=>{try{const name=$('storeNameInput').value.trim();if(!name)throw new Error('店舗名を入力してください');await setSetting('storeName',name);toast('初期設定を保存しました');await goHome();}catch(e){toast(e.message);}};
$('addLocationBtn').onclick=async()=>{await fillLocationOptions();$('locationName').value='';$('locationNumber').value='';$('locationParent').value='';show('locationView');};
$('saveLocationBtn').onclick=async()=>{try{await MasterService.saveLocation({name:$('locationName').value,parentId:$('locationParent').value||null,displayNumber:$('locationNumber').value});toast('保管場所を保存しました');await goHome();}catch(e){toast(e.message);}};
$('addProductBtn').onclick=async()=>{await fillLocationOptions();$('productName').value='';$('productSpec').value='';$('productJan').value='';$('productCasePack').value='1';show('productView');};
$('saveProductBtn').onclick=async()=>{try{await MasterService.saveProduct({name:$('productName').value,spec:$('productSpec').value,jan:$('productJan').value,locationId:$('productLocation').value||null,casePack:$('productCasePack').value});toast('商品を保存しました');await goHome();}catch(e){toast(e.message);}};
$('settingsBtn').onclick=async()=>{$('settingsStoreName').value=await setting('storeName')||'';show('settingsView');};
$('saveSettingsBtn').onclick=async()=>{try{const name=$('settingsStoreName').value.trim();if(!name)throw new Error('店舗名を入力してください');await setSetting('storeName',name);toast('設定を保存しました');await goHome();}catch(e){toast(e.message);}};
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=goHome);
(async()=>{try{await InventoryDB.open();const name=await setting('storeName');if(name)await goHome();else show('setupView');}catch(e){console.error(e);toast('起動に失敗しました: '+e.message);show('setupView');}})();
})();