(()=>{
'use strict';
const FORMAT='inventory-pwa-backup';const SCHEMA_VERSION=4;const STORES=['settings','locations','suppliers','categories','products','lots','transactions'];const DB=()=>window.InventoryDB;function clone(v){return JSON.parse(JSON.stringify(v));}function arrays(data){for(const s of STORES){if(!Array.isArray(data?.[s]))throw new Error(`${s} が配列ではありません`);}}function uniqueIds(items,label,key='id'){const seen=new Set();for(const x of items){const id=x?.[key];if(id==null||id==='')throw new Error(`${label} にID未設定データがあります`);if(seen.has(id))throw new Error(`${label} に重複IDがあります: ${id}`);seen.add(id);}return seen;}
function validateParents(items,label,maxDepth){const byId=new Map(items.map(x=>[x.id,x]));for(const item of items){let cur=item,depth=1;const seen=new Set([item.id]);while(cur.parentId){if(!byId.has(cur.parentId))throw new Error(`${label} ${item.id} の親が存在しません`);if(seen.has(cur.parentId))throw new Error(`${label} ${item.id} が循環参照しています`);seen.add(cur.parentId);cur=byId.get(cur.parentId);depth++;if(depth>maxDepth)throw new Error(`${label} ${item.id} が${maxDepth}階層を超えています`);}}}
function validateData(data){arrays(data);uniqueIds(data.settings,'settings','key');const locationIds=uniqueIds(data.locations,'locations');const supplierIds=uniqueIds(data.suppliers,'suppliers');const categoryIds=uniqueIds(data.categories,'categories');const productIds=uniqueIds(data.products,'products');const lotIds=uniqueIds(data.lots,'lots');uniqueIds(data.transactions,'transactions');validateParents(data.locations,'保管場所',2);validateParents(data.categories,'分類',3);for(const p of data.products){if(p.locationId&&!locationIds.has(p.locationId))throw new Error(`商品 ${p.id} の保管場所が存在しません`);if(p.supplierId&&!supplierIds.has(p.supplierId))throw new Error(`商品 ${p.id} の仕入先が存在しません`);if(p.categoryId&&!categoryIds.has(p.categoryId))throw new Error(`商品 ${p.id} の分類が存在しません`);if(!String(p.name??'').trim())throw new Error(`商品 ${p.id} の商品名がありません`);if(!Number.isInteger(Number(p.casePack))||Number(p.casePack)<1)throw new Error(`商品 ${p.id} のケース入数が不正です`);}for(const l of data.lots){if(!productIds.has(l.productId))throw new Error(`ロット ${l.id} の商品が存在しません`);if(l.locationId&&!locationIds.has(l.locationId))throw new Error(`ロット ${l.id} の保管場所が存在しません`);if(!Number.isInteger(Number(l.qty))||Number(l.qty)<0)throw new Error(`ロット ${l.id} の数量が不正です`);}for(const t of data.transactions){if(t.productId&&!productIds.has(t.productId))throw new Error(`履歴 ${t.id} の商品が存在しません`);if(t.lotId&&!lotIds.has(t.lotId)&&!['使用','廃棄','期限別棚卸','棚卸調整'].includes(t.type))throw new Error(`履歴 ${t.id} のロットが存在しません`);if(t.locationId&&!locationIds.has(t.locationId))throw new Error(`履歴 ${t.id} の保管場所が存在しません`);}return true;}
async function exportData(){const data={};for(const s of STORES)data[s]=clone(await DB().getAll(s));validateData(data);return{format:FORMAT,schemaVersion:SCHEMA_VERSION,appVersion:'2.x',exportedAt:new Date().toISOString(),data};}
function normalizeBackup(input){const obj=typeof input==='string'?JSON.parse(input):clone(input);if(obj?.format!==FORMAT)throw new Error('Ver.2バックアップ形式ではありません');if(obj.schemaVersion!==SCHEMA_VERSION)throw new Error(`未対応のバックアップ形式です: ${obj.schemaVersion}`);validateData(obj.data);return obj;}
async function replaceAll(input){const backup=normalizeBackup(input);const d=await DB().open();return new Promise((resolve,reject)=>{const tx=d.transaction(STORES,'readwrite');try{for(const s of STORES){const store=tx.objectStore(s);store.clear();for(const item of backup.data[s])store.put(clone(item));}}catch(e){try{tx.abort();}catch(_){}reject(e);return;}tx.oncomplete=()=>resolve({schemaVersion:backup.schemaVersion,counts:Object.fromEntries(STORES.map(s=>[s,backup.data[s].length]))});tx.onerror=()=>reject(tx.error||new Error('復元に失敗しました'));tx.onabort=()=>reject(tx.error||new Error('復元を中断しました'));});}
window.BackupService={FORMAT,SCHEMA_VERSION,STORES,validateData,exportData,normalizeBackup,replaceAll};
})();
