(()=>{
'use strict';
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(16).slice(2);
const today=()=>new Date().toISOString().slice(0,10);
function intQty(v,label='数量'){const n=Number(v);if(!Number.isInteger(n)||n<0)throw new Error(`${label}は0以上の整数で指定してください`);return n;}
function expiryKey(l){return l.expiry||'9999-12-31';}
async function mutate(productId,handler){
 const d=await InventoryDB.open();
 return new Promise((resolve,reject)=>{
  const tx=d.transaction(['settings','products','lots','transactions'],'readwrite'),products=tx.objectStore('products'),lots=tx.objectStore('lots'),transactions=tx.objectStore('transactions'),settings=tx.objectStore('settings');
  let result;
  const fail=e=>{try{tx.abort();}catch(_){}reject(e instanceof Error?e:new Error(String(e)));};
  products.get(productId).onsuccess=e=>{
   const product=e.target.result;if(!product){fail(new Error('商品が見つかりません'));return;}
   lots.getAll().onsuccess=le=>{
    try{
     const productLots=(le.target.result||[]).filter(x=>x.productId===productId);
     const storeReq=settings.get('storeName');
     storeReq.onsuccess=()=>{
      try{
       const ctx={product,productLots,lots,transactions,storeName:storeReq.result?.value||'',addHistory(data){transactions.put({id:uid(),timestamp:new Date().toISOString(),productId,lotId:data.lotId||null,locationId:product.locationId||null,type:data.type,qty:Number(data.qty)||0,balance:data.balance??null,reason:data.reason??null,note:data.note??null,unitPrice:null,storeName:this.storeName});}};
       result=handler(ctx);
      }catch(err){fail(err);}
     };
    }catch(err){fail(err);}
   };
  };
  tx.oncomplete=()=>resolve(result);
  tx.onerror=()=>reject(tx.error||new Error('在庫更新に失敗しました'));
  tx.onabort=()=>{};
 });
}
async function receive(productId,rows){if(!Array.isArray(rows)||!rows.length)throw new Error('入荷内容がありません');const clean=rows.map((r,i)=>({qty:intQty(r.qty,`${i+1}行目の数量`),expiry:r.expiry||null})).filter(r=>r.qty>0);if(!clean.length)throw new Error('入荷数量がありません');return mutate(productId,ctx=>{let balance=ctx.productLots.reduce((s,l)=>s+(Number(l.qty)||0),0);for(const row of clean){const lot={id:uid(),productId,locationId:ctx.product.locationId||null,qty:row.qty,expiry:row.expiry,receivedAt:today()};ctx.lots.put(lot);balance+=row.qty;ctx.addHistory({lotId:lot.id,type:'入荷',qty:row.qty,balance,note:row.expiry?`賞味期限 ${row.expiry}`:'期限なし'});}return{balance};});}
async function useFEFO(productId,qty){qty=intQty(qty);if(qty<=0)throw new Error('使用数量は1以上で指定してください');return mutate(productId,ctx=>{const active=ctx.productLots.filter(l=>(Number(l.qty)||0)>0).sort((a,b)=>expiryKey(a).localeCompare(expiryKey(b))||String(a.receivedAt||'').localeCompare(String(b.receivedAt||'')));const total=active.reduce((s,l)=>s+Number(l.qty),0);if(total<qty)throw new Error(`在庫不足です（在庫 ${total} / 使用 ${qty}）`);let remaining=qty,balance=total;for(const lot of active){if(!remaining)break;const take=Math.min(Number(lot.qty),remaining),after=Number(lot.qty)-take;if(after===0)ctx.lots.delete(lot.id);else ctx.lots.put({...lot,qty:after});remaining-=take;balance-=take;ctx.addHistory({lotId:lot.id,type:'使用',qty:-take,balance,note:lot.expiry?`賞味期限 ${lot.expiry}`:'期限なし'});}return{balance};});}
async function discard(productId,lotId,qty,reason,note=''){qty=intQty(qty);if(qty<=0)throw new Error('廃棄数量は1以上で指定してください');return mutate(productId,ctx=>{const lot=ctx.productLots.find(x=>x.id===lotId);if(!lot)throw new Error('対象ロットが見つかりません');if(Number(lot.qty)<qty)throw new Error(`廃棄数量が在庫を超えています（${lot.qty}個）`);const after=Number(lot.qty)-qty;if(after===0)ctx.lots.delete(lot.id);else ctx.lots.put({...lot,qty:after});const balance=ctx.productLots.reduce((s,l)=>s+Number(l.qty||0),0)-qty;ctx.addHistory({lotId,type:'廃棄',qty:-qty,balance,reason:reason||'その他',note});return{balance};});}
async function setLotQty(productId,lotId,target){target=intQty(target,'棚卸数量');return mutate(productId,ctx=>{const lot=ctx.productLots.find(x=>x.id===lotId);if(!lot)throw new Error('対象ロットが見つかりません');const before=Number(lot.qty)||0,diff=target-before;if(!diff)return{balance:ctx.productLots.reduce((s,l)=>s+Number(l.qty||0),0),diff:0};if(target===0)ctx.lots.delete(lot.id);else ctx.lots.put({...lot,qty:target});const balance=ctx.productLots.reduce((s,l)=>s+Number(l.qty||0),0)+diff;ctx.addHistory({lotId,type:'期限別棚卸',qty:diff,balance,note:lot.expiry?`賞味期限 ${lot.expiry}`:'期限なし'});return{balance,diff};});}
async function setProductTotal(productId,target){target=intQty(target,'棚卸数量');return mutate(productId,ctx=>{const active=ctx.productLots.filter(l=>(Number(l.qty)||0)>0).sort((a,b)=>expiryKey(a).localeCompare(expiryKey(b))||String(a.receivedAt||'').localeCompare(String(b.receivedAt||'')));const current=active.reduce((s,l)=>s+Number(l.qty),0),diff=target-current;if(!diff)return{balance:current,diff:0};if(diff>0){ctx.lots.put({id:uid(),productId,locationId:ctx.product.locationId||null,qty:diff,expiry:null,receivedAt:today()});}else{let remaining=-diff;for(const lot of active){if(!remaining)break;const take=Math.min(Number(lot.qty),remaining),after=Number(lot.qty)-take;if(after===0)ctx.lots.delete(lot.id);else ctx.lots.put({...lot,qty:after});remaining-=take;}}ctx.addHistory({type:'棚卸調整',qty:diff,balance:target,note:'商品合計棚卸'});return{balance:target,diff};});}
async function setProductTotals(changes){if(!Array.isArray(changes)||!changes.length)throw new Error('棚卸対象がありません');const clean=changes.map((x,i)=>({productId:String(x.productId||x.id||''),target:intQty(x.target,`${i+1}件目の棚卸数量`)}));if(clean.some(x=>!x.productId))throw new Error('商品IDがありません');if(new Set(clean.map(x=>x.productId)).size!==clean.length)throw new Error('同じ商品が重複しています');const d=await InventoryDB.open();return new Promise((resolve,reject)=>{const tx=d.transaction(['settings','products','lots','transactions'],'readwrite'),products=tx.objectStore('products'),lots=tx.objectStore('lots'),transactions=tx.objectStore('transactions'),settings=tx.objectStore('settings');let result=[];const fail=e=>{try{tx.abort();}catch(_){}reject(e instanceof Error?e:new Error(String(e)));};const getAll=s=>new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});Promise.all([getAll(products),getAll(lots),new Promise((res,rej)=>{const r=settings.get('storeName');r.onsuccess=()=>res(r.result?.value||'');r.onerror=()=>rej(r.error);})]).then(([allProducts,allLots,storeName])=>{try{const productMap=new Map(allProducts.map(p=>[p.id,p]));for(const item of clean){const product=productMap.get(item.productId);if(!product)throw new Error('商品が見つかりません');const active=allLots.filter(l=>l.productId===item.productId&&(Number(l.qty)||0)>0).sort((a,b)=>expiryKey(a).localeCompare(expiryKey(b))||String(a.receivedAt||'').localeCompare(String(b.receivedAt||''))),current=active.reduce((s,l)=>s+Number(l.qty),0),diff=item.target-current;if(!diff){result.push({productId:item.productId,balance:current,diff:0});continue;}if(diff>0){lots.put({id:uid(),productId:item.productId,locationId:product.locationId||null,qty:diff,expiry:null,receivedAt:today()});}else{let remaining=-diff;for(const lot of active){if(!remaining)break;const take=Math.min(Number(lot.qty),remaining),after=Number(lot.qty)-take;if(after===0)lots.delete(lot.id);else lots.put({...lot,qty:after});remaining-=take;}}transactions.put({id:uid(),timestamp:new Date().toISOString(),productId:item.productId,lotId:null,locationId:product.locationId||null,type:'棚卸調整',qty:diff,balance:item.target,reason:null,note:'商品合計棚卸',unitPrice:null,storeName});result.push({productId:item.productId,balance:item.target,diff});}}catch(e){fail(e);}}).catch(fail);tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error||new Error('一括棚卸に失敗しました'));tx.onabort=()=>{};});}
window.InventoryService={receive,useFEFO,discard,setLotQty,setProductTotal,setProductTotals};
})();