(()=>{
'use strict';
const ZXING_URL='https://unpkg.com/@zxing/browser@0.2.1/umd/zxing-browser.min.js';
const cameraSupported=!!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia);const nativeSupported='BarcodeDetector'in window;let overlay=null,video=null,stream=null,raf=null,detector=null,zxingControls=null,zxingLoading=null,busy=false;
const normalize=v=>String(v??'').replace(/\D/g,'');const valid=v=>[8,12,13].includes(normalize(v).length);
function status(main,sub=''){if(!overlay)return;const a=overlay.querySelector('#v2JanMain'),b=overlay.querySelector('#v2JanSub');if(a)a.textContent=main;if(b)b.textContent=sub;}
async function stop(){if(raf)cancelAnimationFrame(raf);raf=null;if(zxingControls){try{zxingControls.stop();}catch(e){}zxingControls=null;}if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;detector=null;video=null;if(overlay)overlay.remove();overlay=null;busy=false;}
function createOverlay(mode){overlay=document.createElement('div');overlay.style='position:fixed;inset:0;background:#000;z-index:10000;display:flex;flex-direction:column';overlay.innerHTML=`<div style="padding:12px;background:#111;color:#fff;display:flex;gap:10px;align-items:center"><div style="flex:1"><strong>JANコードを枠内へ</strong><div style="font-size:12px;opacity:.8">${mode}</div></div><button id="v2JanClose" type="button" style="min-height:44px">閉じる</button></div><div style="position:relative;flex:1;overflow:hidden"><video id="v2JanVideo" autoplay playsinline muted style="width:100%;height:100%;object-fit:cover"></video><div style="position:absolute;left:5%;right:5%;top:36%;height:20%;border:4px solid #fff;border-radius:10px;box-shadow:0 0 0 9999px rgba(0,0,0,.2)"></div><div style="position:absolute;left:6%;right:6%;bottom:6%;padding:12px;background:rgba(17,24,39,.9);color:#fff;text-align:center;border-radius:12px"><div id="v2JanMain" style="font-weight:800">カメラを準備しています…</div><div id="v2JanSub" style="font-size:12px;margin-top:5px"></div></div></div>`;document.body.appendChild(overlay);video=overlay.querySelector('#v2JanVideo');overlay.querySelector('#v2JanClose').onclick=stop;}
async function accept(raw){if(busy)return;const code=normalize(raw);if(!valid(code)){status('JANとして確定できません','8・12・13桁のコードを読み取ってください');return;}busy=true;status('読み取りました ✓',`JAN ${code}`);const input=document.getElementById('productJan');if(input){input.value=code;input.dispatchEvent(new Event('input',{bubbles:true}));}await new Promise(r=>setTimeout(r,250));await stop();}
function loadZXing(){if(window.ZXingBrowser)return Promise.resolve(window.ZXingBrowser);if(zxingLoading)return zxingLoading;zxingLoading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=ZXING_URL;s.async=true;s.onload=()=>window.ZXingBrowser?resolve(window.ZXingBrowser):reject(new Error('ZXing読込失敗'));s.onerror=()=>reject(new Error('ZXing取得失敗'));document.head.appendChild(s);});return zxingLoading;}
async function nativeScan(){createOverlay('標準カメラ読取');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});status('バーコードを探しています…','枠内にバーコード全体を入れてください');const loop=async()=>{if(!video||!detector)return;try{const codes=await detector.detect(video);if(codes.length){await accept(codes[0].rawValue);return;}}catch(e){}raf=requestAnimationFrame(loop);};loop();}
async function zxingScan(){createOverlay('互換カメラ読取');status('読取機能を準備しています…','初回は数秒かかる場合があります');const ZX=await loadZXing();const Reader=ZX.BrowserMultiFormatOneDReader||ZX.BrowserMultiFormatReader;if(!Reader)throw new Error('1D readerなし');const reader=new Reader();zxingControls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false},video,(result,error,controls)=>{if(result&&!busy){zxingControls=controls;accept(result.getText?result.getText():result.text||'');}});stream=video?.srcObject||null;status('バーコードを探しています…','枠内にバーコード全体を入れてください');}
function manual(){const current=document.getElementById('productJan')?.value||'';const v=prompt('JANコードを入力してください。',current);if(v==null)return;const code=normalize(v);if(!valid(code)){alert('JANコードは8・12・13桁で入力してください。');return;}const input=document.getElementById('productJan');if(input)input.value=code;}
async function start(){if(!cameraSupported){manual();return;}try{if(nativeSupported)await nativeScan();else await zxingScan();}catch(e){console.warn('Ver2 JAN scanner',e);await stop();manual();}}
function setup(){const input=document.getElementById('productJan');if(!input||document.getElementById('v2JanScanBtn'))return;const wrap=document.createElement('div');wrap.style='display:flex;gap:8px;align-items:center';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);input.style.flex='1';const btn=document.createElement('button');btn.id='v2JanScanBtn';btn.type='button';btn.className='secondary';btn.textContent=cameraSupported?'JAN読取':'JAN入力';btn.onclick=start;wrap.appendChild(btn);const note=document.createElement('small');note.className='note';note.textContent=nativeSupported&&cameraSupported?'標準カメラ読取対応':cameraSupported?'互換カメラ読取対応':'カメラ非対応のため手入力';wrap.parentNode.appendChild(note);}
setup();window.Ver2JanScanner={start,stop,normalize,valid};
})();