(()=>{
'use strict';
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(16).slice(2);const clone=v=>JSON.parse(JSON.stringify(v));const text=v=>String(v??'').trim();
function parse(input){const d=typeof input==='string'?JSON.parse(input):clone(input);if(d?.app!=='在庫賞味期限管理')throw new Error('Ver.1バックアップ形式ではありません');if(!Array.isArray(d.settings)||!Array.isArray(d.locations)||!Array.isArray(d.products)||!Array.isArray(d.lots))throw new Error('Ver.1バックアップに必要なデータがありません');d.categories=Array.isArray(d.categories)?d.categories:[];d.transactions=Array.isArray(d.transactions)?d.transactions:[];return d;}
function supplierRecords(old,extra=[]){const map=new Map();const add=(name,active=true)=>{name=text(name);if(!name)return;const key=name.normalize('NFKC').toLowerCase();if(!map.has(key))map.set(key,{id:uid(),name,active:active!==false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});};for(const s of extra||[])add(typeof s==='string'?s:s?.name,typeof s==='string'?true:s?.active);for(const p of old.products)add(p.supplier,true);return[...map.values()];}
function convert(input,options={}){const old=parse(input);const now=new Date().toISOString();const warnings=[];const suppliers=supplierRecords(old,options.suppliers||[]);const supplierByName=new Map(suppliers.map(s=>[s.name.normalize('NFKC').toLowerCase(),s]));const settings=old.settings.map(x=>clone(x)).filter(x=>x.key!=='suppliers');const set=(key,value)=>{const i=settings.findIndex(x=>x.key===key);if(i>=0)settings[i]={key,value};else settings.push({key,value});};if(options.locationSortMode)set('locationSortMode',options.locationSortMode);if(options.locationNumbers)set('legacyLocationNumbers',clone(options.locationNumbers));const locations=old.locations.map((l,i)=>({...clone(l),parentId:l.parentId??l.parentLocationId??null,displayNumber:options.locationNumbers?.[l.id]??l.displayNumber??null,order:Number.isFinite(Number(l.order))?Number(l.order):i,active:l.active!==false,createdAt:l.createdAt||now,updatedAt:l.updatedAt||now}));const categories=old.categories.map(c=>({...clone(c),parentId:c.parentId??null,active:c.active!==false,createdAt:c.createdAt||now,updatedAt:c.updatedAt||now}));const products=old.products.map(p=>{const name=text(p.supplier);const supplier=name?supplierByName.get(name.normalize('NFKC').toLowerCase()):null;return{...clone(p),name:text(p.name),jan:String(p.jan??'').replace(/\D/g,''),supplierId:supplier?.id||null,supplier:name,casePack:Math.max(1,Math.floor(Number(p.casePack)||1)),locationId:p.locationId||null,categoryId:p.categoryId||null,active:p.active!==false,createdAt:p.createdAt||now,updatedAt:p.updatedAt||now};});const productLocation=new Map(products.map(p=>[p.id,p.locationId]));const lots=[];for(const l of old.lots){const qty=Math.floor(Number(l.qty)||0);if(qty<=0){warnings.push(`数量0以下のロットを除外: ${l.id}`);continue;}lots.push({...clone(l),qty,expiry:l.expiry||null,locationId:l.locationId||productLocation.get(l.productId)||null});}const lotIds=new Set(lots.map(l=>l.id));const transactions=old.transactions.map(t=>{const item=clone(t);if(item.lotId&&!lotIds.has(item.lotId)){item.legacyLotId=item.lotId;item.lotId=null;warnings.push(`履歴の削除済みロット参照を保持情報へ移動: ${item.id}`);}if(item.locationId==null&&item.productId)item.locationId=productLocation.get(item.productId)||null;return item;});const data={settings,locations,suppliers,categories,products,lots,transactions};window.BackupService.validateData(data);return{format:window.BackupService.FORMAT,schemaVersion:window.BackupService.SCHEMA_VERSION,appVersion:'2.x',exportedAt:new Date().toISOString(),migratedFrom:{app:old.app,schemaVersion:old.schemaVersion??null,exportedAt:old.exportedAt??null},migrationReport:{sourceCounts:{locations:old.locations.length,categories:old.categories.length,products:old.products.length,lots:old.lots.length,transactions:old.transactions.length},targetCounts:{locations:locations.length,suppliers:suppliers.length,categories:categories.length,products:products.length,lots:lots.length,transactions:transactions.length},warnings},data};}
async function importVer1(input,options={}){const converted=convert(input,options);const result=await window.BackupService.replaceAll(converted);return{...result,migratedFrom:converted.migratedFrom,migrationReport:converted.migrationReport};}
window.MigrationService={parse,convert,importVer1};
})();
